[package]
name = "rust_calc"
version = "0.1.0"
authors = ["Belchior Oliveira <belchior.oliveira@omegaenergia.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k9 = "0.10.3"